[build]
  # Install dependencies for sub-packages before building
  command = "NPM_CONFIG_PRODUCTION=false npm --prefix frontend ci && npm --prefix backend ci || true && npm run build:all"
  publish = "frontend/dist"

[build.environment]
  # Ensure devDependencies (like vite) are installed during build
  NPM_CONFIG_PRODUCTION = "false"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/ice"
  to = "/.netlify/functions/ice"
  status = 200
